version: "3.8"

services:
    pg1-game7:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "p0stgr35!"
        ports:
            - "5433:5432"
        volumes:
            - /Users/luizamorim/postgres/db:/var/lib/postgresql/data
        networks:
            - postgres-network-game7

    pgadmin1-game7:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: "user@domain.com"
            PGADMIN_DEFAULT_PASSWORD: "5up3r53cret!"
        ports:
            - "8082:80"
        depends_on:
            - pg1-game7
        networks:
            - postgres-network-game7

    game7:
        build:
            context: .
            args:
                - DATABASE_URL=${DATABASE_URL}
        ports:
            - "5001:5001"
        environment:
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - pg1-game7
        networks:
            - postgres-network-game7

networks:
    postgres-network-game7:
        driver: bridge
