name: Build and Push Docker Image to GitHub Dev Registry

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.PERSONAL_TOKEN }}

            - name: Extract package version
              run: echo "PACKAGE_VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ghcr.io/${{ github.repository }}:${{ env.PACKAGE_VERSION }}-rc.1
                  build-args: POSTGRES_PRISMA_URL=${{ secrets.DATABASE_URL }}
